name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build Binaries
        run: |
          PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64"
          for platform in $PLATFORMS; do
            GOOS=$(echo $platform | cut -d'/' -f1)
            GOARCH=$(echo $platform | cut -d'/' -f2)
            
            # Construct binary name with ghmon prefix
            BIN_NAME="ghmon-$GOOS-$GOARCH"
            
            # On Windows, append .exe
            if [ "$GOOS" = "windows" ]; then
              BIN_NAME="$BIN_NAME.exe"
            fi

            echo "Building for $GOOS/$GOARCH -> $BIN_NAME"
            GOOS=$GOOS GOARCH=$GOARCH go build -o $BIN_NAME .
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # Upload all files that start with ghmon-
          files: |
            ghmon-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
