name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.4"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ghmon-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ghmon-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
