name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23.x

      - uses: goreleaser/goreleaser-action@v5
        with:
          args: "release --clean"
          version: latest
          workdir: .
